### ISSUE TITLE
Use of assets in non-profit and/or commercial projects

### ISSUE THREAD

**Issue by ZiadJ** [Norad-Eduapp4syria/Norad-Eduapp4syria#2]
I really like the models and animations for Antura and the living letters. Great job guys and thanks for opening it up to the world!!! 

Right now I'm working on an educational game that's focused on teaching kids the basics of the arabic language and some of the assets in this project would be a perfect fit for it. The game will be free at launch but I could probably add new paid levels later. I'm not sure about how it's copyrighted though so it would help if someone could clarify on the permissions I have in that respect.

**Comment by StefanoCecere** [comment]
hi @ZiadJ 
since you are talking about Antura (the project i maintain) i'll reply here:
all the EA4S projects are released under the BSD/Creative Commons licenses.
you can do pratically anything with the code and assets, even in commercial projects, as far as you give credits to the original project.

to simplify: just add in the credits something like: 
"these assets (secipy.. like UI, model, music etc)" are from the Eduapp4syria  - Antura project (by TH Köln / Cologne Game Lab, Video Games Without Borders & Wixel Studios) is licensed under CC BY 4.0 - https://github.com/vgwb/Antura_arabic

you can check the Creative Commons site for more details.. or get back to me whenever you publish your product! https://creativecommons.org/use-remix/get-permission/

good work!

stefano
